// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strings"

	"github.com/arran4/go-subcommand/examples/io_types/app"
	"github.com/arran4/go-subcommand/examples/io_types/cmd"
)

var _ Cmd = (*CopyFile)(nil)

type CopyFile struct {
	*RootCmd
	Flags         *flag.FlagSet
	input         io.Reader
	output        io.Writer
	SubCommands   map[string]func() Cmd
	CommandAction func(c *CopyFile) error
}

type UsageDataCopyFile struct {
	*CopyFile
	Recursive bool
}

func (c *CopyFile) Usage() {
	err := executeUsage(os.Stderr, "copy-file_usage.txt", UsageDataCopyFile{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *CopyFile) UsageRecursive() {
	err := executeUsage(os.Stderr, "copy-file_usage.txt", UsageDataCopyFile{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *CopyFile) Execute(args []string) error {
	var cleanups []func() error
	defer func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			_ = cleanups[i]()
		}
	}()
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 2 {
		return fmt.Errorf("expected at least 2 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument input
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			if argVal == "-" {
				c.input = os.Stdin
			} else {
				f, err := os.Open(argVal)
				if err != nil {
					return err
				}
				cleanups = append(cleanups, f.Close)
				c.input = f
			}
		} else {
		}
	}
	// Handle positional argument output
	{
		argIndex := 1
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			if argVal == "-" {
				c.output = os.Stdout
			} else {
				f, err := os.OpenFile(argVal, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
				if err != nil {
					return err
				}
				cleanups = append(cleanups, f.Close)
				c.output = f
			}
		} else {
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("copy-file failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewCopyFile() *CopyFile {
	set := flag.NewFlagSet("copy-file", flag.ContinueOnError)
	v := &CopyFile{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *CopyFile) error {

		err := app.RunCopyFile(c.input, c.output)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("copy-file failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
