// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package io_types

import (
	"errors"
	"flag"
	"fmt"
	"github.com/arran4/go-subcommand/examples/io_types/app"
	"github.com/arran4/go-subcommand/examples/io_types/cmd"
	"io"
	"os"
	"slices"
	"strings"
)

var _ Cmd = (*InspectFile)(nil)

type InspectFile struct {
	*RootCmd
	Flags         *flag.FlagSet
	file          *os.File
	SubCommands   map[string]func() Cmd
	CommandAction func(c *InspectFile) error
}

type UsageDataInspectFile struct {
	*InspectFile
	Recursive bool
}

func (c *InspectFile) Usage() {
	err := executeUsage(os.Stderr, "inspect-file_usage.txt", UsageDataInspectFile{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *InspectFile) UsageRecursive() {
	err := executeUsage(os.Stderr, "inspect-file_usage.txt", UsageDataInspectFile{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *InspectFile) Execute(args []string) error {
	var closers []io.Closer
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument file
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			if argVal == "-" || argVal == "stdin" {
				c.file = os.Stdin
			} else {
				f, err := os.Open(argVal)
				if err != nil {
					return err
				}
				closers = append(closers, f)
				c.file = f
			}
		} else {
		}
	}

	if c.CommandAction != nil {
		defer func() {
			for _, cl := range closers {
				_ = cl.Close()
			}
		}()
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("inspect-file failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewInspectFile() *InspectFile {
	set := flag.NewFlagSet("inspect-file", flag.ContinueOnError)
	v := &InspectFile{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}
	var closers []io.Closer
	set.Usage = v.Usage

	v.CommandAction = func(c *InspectFile) error {
		defer func() {
			for _, cl := range closers {
				_ = cl.Close()
			}
		}()

		err := app.RunInspectFile(c.file)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("inspect-file failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
