// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

//go:generate sh -c "command -v gosubc >/dev/null 2>&1 && gosubc generate || go run github.com/arran4/go-subcommand/cmd/gosubc generate"

import (
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/io_types/cmd"
)

var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

// Provenance
var (
	GeneratorVersion = "v0.0.28-0.20260826070241-a1822411390f+dirty"
	GeneratedAt      = ""
	ProjectCommit    = ""
)

func main() {
	root, err := NewRoot("io_types", version, commit, date)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := root.Execute(os.Args[1:]); err != nil {
		if e, ok := err.(*cmd.ErrExitCode); ok {
			if e.Err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", e.Err)
			}
			os.Exit(e.Code)
		}
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
