// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package io_types

//go:generate sh -c "command -v gosubc >/dev/null 2>&1 && gosubc generate || go run github.com/arran4/go-subcommand/cmd/gosubc generate"

import (
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/io_types/cmd"
)

var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

// Provenance
var (
	GeneratorVersion = "v0.0.28-0.20260821032812-9ae5d239453d+dirty"
	GeneratedAt      = "2026-08-24T01:16:32Z"
	ProjectCommit    = "9ae5d239453d68308fb9c19a217feac432baff8a"
)

func main() {
	root, err := NewRoot("io_types", version, commit, date)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := root.Execute(os.Args[1:]); err != nil {
		if e, ok := err.(*cmd.ErrExitCode); ok {
			if e.Err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", e.Err)
			}
			os.Exit(e.Code)
		}
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
