// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package app

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strconv"
	"sync"

	"github.com/arran4/go-subcommand/examples/go-flag-test/cmd"
	"github.com/arran4/go-subcommand/examples/go-flag-test/cmd/app/templates"
	"github.com/arran4/go-subcommand/examples/go-flag-test/internal/myapp"
)

var generatedOpenReader = func(name string) (io.ReadCloser, error) {
	return os.Open(name)
}

var generatedOpenWriter = func(name string) (io.WriteCloser, error) {
	return os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
}

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

func NewLazyCommand(f func() Cmd) func() Cmd {
	var once sync.Once
	var cmd Cmd
	return func() Cmd {
		once.Do(func() {
			cmd = f()
		})
		return cmd
	}
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data any) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]func() Cmd
	Version       string
	Commit        string
	Date          string
	in            io.Reader
	out           io.Writer
	verbose       bool
	a             bool
	b             bool
	c             bool
	pointerInt    *int
	args          []string
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *RootCmd) UsageRecursive() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

type UsageDataRootCmd struct {
	*RootCmd
	Recursive bool
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]func() Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.Func("in", "Input source", func(s string) error {
		// Parsed manually in Execute
		return nil
	})

	c.Func("out", "Output target", func(s string) error {
		// Parsed manually in Execute
		return nil
	})

	c.BoolVar(&c.verbose, "verbose", false, "Verbose")

	c.BoolVar(&c.a, "a", false, "TODO: Add usage text")

	c.BoolVar(&c.b, "b", false, "TODO: Add usage text")

	c.BoolVar(&c.c, "c", false, "TODO: Add usage text")

	c.Func("pointerInt", "TODO: Add usage text", func(s string) error {
		parsed, err := strconv.Atoi(s)
		if err != nil {
			return err
		}
		val := parsed
		c.pointerInt = &val
		return nil
	})

	c.Var((*StringSlice)(&c.args), "args", "(positional: true)")

	c.CommandAction = func(c *RootCmd) error {

		err := myapp.App(c.in, c.out, c.verbose, c.a, c.b, c.c, c.pointerInt, c.args)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("app failed: %w", err)
		}
		return nil
	}

	{
		subCmd := NewLazyCommand(func() Cmd { return c.NewChild() })
		c.Commands["child"] = subCmd

	}
	c.Commands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["version"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
				return nil
			},
			UsageFunc: func() {
				fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
			},
		}
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) (err error) {
	var cleanups []func() error
	defer func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			if cerr := cleanups[i](); cerr != nil && err == nil {
				err = cerr
			}
		}
	}()
	var remainingArgs []string
	dashDashSeen := false
	// Check if -- is passed before positionals. We need to evaluate whether flag parsing stopped due to -- or due to positional.
	// FlagSet will consume -- and stop. So if we have remaining args and -- was present right where FlagSet stopped, it saw it.

	c.FlagSet = flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	c.FlagSet.Usage = c.Usage
	seenFlags := make(map[string]bool)

	// Create a local flagset so it doesn't ExitOnError or panic
	fs := flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	fs.Usage = c.Usage

	fs.Var(goFlagCustom(func(s string) error {
		value := s
		if value == "-" {
			c.in = os.Stdin
		} else {
			f, err := generatedOpenReader(value)
			if err != nil {
				return err
			}
			cleanups = append(cleanups, f.Close)
			c.in = f
		}
		return nil
	}, false), "in", "Input source")

	fs.Var(goFlagCustom(func(s string) error {
		value := s
		if value == "-" {
			c.out = os.Stdout
		} else {
			f, err := generatedOpenWriter(value)
			if err != nil {
				return err
			}
			cleanups = append(cleanups, f.Close)
			c.out = f
		}
		return nil
	}, false), "out", "Output target")

	fs.BoolVar(&c.verbose, "verbose", c.verbose, "Verbose")

	fs.BoolVar(&c.a, "a", c.a, "")

	fs.BoolVar(&c.b, "b", c.b, "")

	fs.BoolVar(&c.c, "c", c.c, "")

	fs.Var(goFlagCustom(func(s string) error {
		iv, err := strconv.Atoi(s)
		if err != nil {
			return err
		}
		c.pointerInt = &iv
		return nil
	}, false), "pointerInt", "")

	fs.Var((*StringSlice)(&c.args), "args", "(positional: true)")

	err = fs.Parse(args)
	if err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}

	seenFlags["in"] = false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == "in" {
			seenFlags["in"] = true
		}
	})

	seenFlags["out"] = false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == "out" {
			seenFlags["out"] = true
		}
	})

	remainingArgs = fs.Args()

	// Check exactly why flagset stopped parsing
	parsedArgsCount := len(args) - len(remainingArgs)
	if parsedArgsCount < len(args) && args[parsedArgsCount] == "--" {
		dashDashSeen = true
	} else if parsedArgsCount > 0 && args[parsedArgsCount-1] == "--" {
		dashDashSeen = true
	}
	if !seenFlags["in"] {
		if "-" == "-" {
			c.in = os.Stdin
		} else {
			f, err := generatedOpenReader("-")
			if err != nil {
				return err
			}
			cleanups = append(cleanups, f.Close)
			c.in = f
		}
	}
	if !seenFlags["out"] {
		if "-" == "-" {
			c.out = os.Stdout
		} else {
			f, err := generatedOpenWriter("-")
			if err != nil {
				return err
			}
			cleanups = append(cleanups, f.Close)
			c.out = f
		}
	}
	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("app failed: %w", err)
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	return nil
}
