// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strconv"
	"strings"
	"sync"

	"github.com/arran4/go-subcommand/examples/go-flag-test/cmd"
	"github.com/arran4/go-subcommand/examples/go-flag-test/cmd/app/templates"
	"github.com/arran4/go-subcommand/examples/go-flag-test/internal/myapp"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

func NewLazyCommand(f func() Cmd) func() Cmd {
	var once sync.Once
	var cmd Cmd
	return func() Cmd {
		once.Do(func() {
			cmd = f()
		})
		return cmd
	}
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data any) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]func() Cmd
	Version       string
	Commit        string
	Date          string
	in            string
	out           string
	verbose       bool
	a             bool
	b             bool
	c             bool
	args          []string
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *RootCmd) UsageRecursive() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

type UsageDataRootCmd struct {
	*RootCmd
	Recursive bool
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]func() Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.StringVar(&c.in, "in", "stdin", "Input source")

	c.StringVar(&c.out, "out", "stdout", "Output target")

	c.BoolVar(&c.verbose, "verbose", false, "Verbose")

	c.BoolVar(&c.a, "a", false, "TODO: Add usage text")

	c.BoolVar(&c.b, "b", false, "TODO: Add usage text")

	c.BoolVar(&c.c, "c", false, "TODO: Add usage text")

	c.Var((*StringSlice)(&c.args), "args", "(positional: true)")

	c.CommandAction = func(c *RootCmd) error {

		err := myapp.App(c.in, c.out, c.verbose, c.a, c.b, c.c, c.args)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("app failed: %w", err)
		}
		return nil
	}

	{
		subCmd := NewLazyCommand(func() Cmd { return c.NewChild() })
		c.Commands["child"] = subCmd

	}
	c.Commands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["version"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
				return nil
			},
			UsageFunc: func() {
				fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
			},
		}
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg[1:]
			if strings.HasPrefix(name, "-") {
				name = name[1:]
			}
			if name == "help" || name == "h" {
				c.Usage()
				return nil
			}

			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}

			_ = value
			_ = hasValue

			found := false
			switch name {

			case "in":
				found = true
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.in = value

			case "out":
				found = true
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.out = value

			case "verbose":
				found = true
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.verbose = b
				} else {
					c.verbose = true
				}

			case "a":
				found = true
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.a = b
				} else {
					c.a = true
				}

			case "b":
				found = true
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.b = b
				} else {
					c.b = true
				}

			case "c":
				found = true
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.c = b
				} else {
					c.c = true
				}

			case "args":
				found = true
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.args = append(c.args, value)
			default:
				// Try to see if it's a combined boolean short flag, only if single dash was used.
				// Actually, go-flag doesn't do GNU-style short flag clustering. It just looks for the exact name.
				// If not found, it's an error.
			}

			if !found {
				return fmt.Errorf("unknown flag: -%s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}
	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("app failed: %w", err)
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	return nil
}
