// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	called := false
	cmd.CommandAction = func(c *RootCmd) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--in")
	args = append(args, "test")
	args = append(args, "--out")
	args = append(args, "test")
	args = append(args, "--verbose")
	args = append(args, "-a")
	args = append(args, "-b")
	args = append(args, "-c")
	args = append(args, "--args")
	args = append(args, "test")

	err = cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.in != "test" {
		t.Errorf("Expected in to be 'test', got '%v'", cmd.in)
	}
	if cmd.out != "test" {
		t.Errorf("Expected out to be 'test', got '%v'", cmd.out)
	}
	if cmd.verbose != true {
		t.Errorf("Expected verbose to be true, got '%v'", cmd.verbose)
	}
	if cmd.a != true {
		t.Errorf("Expected a to be true, got '%v'", cmd.a)
	}
	if cmd.b != true {
		t.Errorf("Expected b to be true, got '%v'", cmd.b)
	}
	if cmd.c != true {
		t.Errorf("Expected c to be true, got '%v'", cmd.c)
	}

}

func TestRoot_ExecuteHelpAndUnknownFlags(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
