# .goreleaser.yml
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gosubc
    binary: gosubc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: gosubc
    package_name: gosubc
    homepage: https://github.com/arran4/go-subcommand
    maintainer: Arran Ubels <arran@ubels.org>
    description: Go Subcommand generator.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/arran4/go-subcommand:{{ .Version }}-amd64"
      - "ghcr.io/arran4/go-subcommand:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/arran4/go-subcommand:{{ .Version }}-arm64"
      - "ghcr.io/arran4/go-subcommand:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: ghcr.io/arran4/go-subcommand:{{ .Version }}
    image_templates:
      - ghcr.io/arran4/go-subcommand:{{ .Version }}-amd64
      - ghcr.io/arran4/go-subcommand:{{ .Version }}-arm64
  - name_template: ghcr.io/arran4/go-subcommand:latest
    image_templates:
      - ghcr.io/arran4/go-subcommand:latest-amd64
      - ghcr.io/arran4/go-subcommand:latest-arm64
