# This Dockerfile is used by GoReleaser to build container images.
# GoReleaser builds the binary first and then copies it into the image,
# so no build step is required here.
# This image contains the goa4web binary.
FROM scratch
ENV PATH=/usr/local/bin
COPY gosubc /usr/local/bin/gosubc
ENTRYPOINT ["/usr/local/bin/gosubc"]
