import re

with open("templates/common/common.gotmpl", "r") as f:
    content = f.read()

# Replace provenance
content = re.sub(
    r'{{- define "provenance" -}}\n// Code generated by github.com/arran4/go-subcommand/cmd/gosubc.*? DO NOT EDIT\.\n{{- if \. }}\n{{- if or \.Commit \.Timestamp \.ProjectCommit \.ReplacedTemplates }}\n//\n{{- if \.Commit }}\n// Generator Commit: {{ \.Commit }}{{ if \.Dirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.Timestamp }}\n// Generated: {{ \.Timestamp }}\n{{- end }}\n{{- if \.ProjectCommit }}\n// Project Commit: {{ \.ProjectCommit }}{{ if \.ProjectDirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.ReplacedTemplates }}\n// Templates: Replaced \(ID: {{ \.TemplateID }}\)\n{{- else }}\n// Templates: Built-in\n{{- end }}\n{{- end }}\n{{- end }}\n{{- end -}}',
    """{{- define "provenance" -}}
// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.
{{- if . }}
{{- if or .Version .Commit .Timestamp .ProjectCommit .ReplacedTemplates }}
//
// Provenance:
{{- if .Version }}
// - Version: {{ .Version }}
{{- end }}
{{- if .Commit }}
// - Generator Commit: {{ .Commit }}{{ if .Dirty }} (dirty){{ end }}
{{- end }}
{{- if .Timestamp }}
// - Generated: {{ .Timestamp }}
{{- end }}
{{- if .ProjectCommit }}
// - Project Commit: {{ .ProjectCommit }}{{ if .ProjectDirty }} (dirty){{ end }}
{{- end }}
{{- if .ReplacedTemplates }}
// - Templates: Replaced (ID: {{ .TemplateID }})
{{- else }}
// - Templates: Built-in
{{- end }}
{{- end }}
{{- end }}
{{- end -}}""",
    content
)

# Replace provenance_comment
content = re.sub(
    r'{{- define "provenance_comment" -}}\n<!-- Code generated by github.com/arran4/go-subcommand/cmd/gosubc.*? DO NOT EDIT\. -->\n{{- if \. }}\n{{- if or \.Commit \.Timestamp \.ProjectCommit \.ReplacedTemplates }}\n<!--\n{{- if \.Commit }}\n  Generator Commit: {{ \.Commit }}{{ if \.Dirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.Timestamp }}\n  Generated: {{ \.Timestamp }}\n{{- end }}\n{{- if \.ProjectCommit }}\n  Project Commit: {{ \.ProjectCommit }}{{ if \.ProjectDirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.ReplacedTemplates }}\n  Templates: Replaced \(ID: {{ \.TemplateID }}\)\n{{- else }}\n  Templates: Built-in\n{{- end }}\n-->\n{{- end }}\n{{- end }}\n{{- end -}}',
    """{{- define "provenance_comment" -}}
<!-- Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT. -->
{{- if . }}
{{- if or .Version .Commit .Timestamp .ProjectCommit .ReplacedTemplates }}
<!--
  Provenance:
{{- if .Version }}
  - Version: {{ .Version }}
{{- end }}
{{- if .Commit }}
  - Generator Commit: {{ .Commit }}{{ if .Dirty }} (dirty){{ end }}
{{- end }}
{{- if .Timestamp }}
  - Generated: {{ .Timestamp }}
{{- end }}
{{- if .ProjectCommit }}
  - Project Commit: {{ .ProjectCommit }}{{ if .ProjectDirty }} (dirty){{ end }}
{{- end }}
{{- if .ReplacedTemplates }}
  - Templates: Replaced (ID: {{ .TemplateID }})
{{- else }}
  - Templates: Built-in
{{- end }}
-->
{{- end }}
{{- end }}
{{- end -}}""",
    content
)

# Replace provenance_man
content = re.sub(
    r'{{- define "provenance_man" -}}\n\\." Code generated by github.com/arran4/go-subcommand/cmd/gosubc.*? DO NOT EDIT\.\n{{- if \. }}\n{{- if or \.Commit \.Timestamp \.ProjectCommit \.ReplacedTemplates }}\n\\."\n{{- if \.Commit }}\n\\." Generator Commit: {{ \.Commit }}{{ if \.Dirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.Timestamp }}\n\\." Generated: {{ \.Timestamp }}\n{{- end }}\n{{- if \.ProjectCommit }}\n\\." Project Commit: {{ \.ProjectCommit }}{{ if \.ProjectDirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.ReplacedTemplates }}\n\\." Templates: Replaced \(ID: {{ \.TemplateID }}\)\n{{- else }}\n\\." Templates: Built-in\n{{- end }}\n{{- end }}\n{{- end }}\n{{- end -}}',
    """{{- define "provenance_man" -}}
.\\" Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.
{{- if . }}
{{- if or .Version .Commit .Timestamp .ProjectCommit .ReplacedTemplates }}
.\\"
.\\" Provenance:
{{- if .Version }}
.\\" - Version: {{ .Version }}
{{- end }}
{{- if .Commit }}
.\\" - Generator Commit: {{ .Commit }}{{ if .Dirty }} (dirty){{ end }}
{{- end }}
{{- if .Timestamp }}
.\\" - Generated: {{ .Timestamp }}
{{- end }}
{{- if .ProjectCommit }}
.\\" - Project Commit: {{ .ProjectCommit }}{{ if .ProjectDirty }} (dirty){{ end }}
{{- end }}
{{- if .ReplacedTemplates }}
.\\" - Templates: Replaced (ID: {{ .TemplateID }})
{{- else }}
.\\" - Templates: Built-in
{{- end }}
{{- end }}
{{- end }}
{{- end -}}""",
    content
)

# Replace provenance_yml
content = re.sub(
    r'{{- define "provenance_yml" -}}\n# Code generated by github.com/arran4/go-subcommand/cmd/gosubc.*? DO NOT EDIT\.\n{{- if \. }}\n{{- if or \.Commit \.Timestamp \.ProjectCommit \.ReplacedTemplates }}\n#\n{{- if \.Commit }}\n# Generator Commit: {{ \.Commit }}{{ if \.Dirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.Timestamp }}\n# Generated: {{ \.Timestamp }}\n{{- end }}\n{{- if \.ProjectCommit }}\n# Project Commit: {{ \.ProjectCommit }}{{ if \.ProjectDirty }} \(dirty\){{ end }}\n{{- end }}\n{{- if \.ReplacedTemplates }}\n# Templates: Replaced \(ID: {{ \.TemplateID }}\)\n{{- else }}\n# Templates: Built-in\n{{- end }}\n{{- end }}\n{{- end }}\n{{- end -}}',
    """{{- define "provenance_yml" -}}
# Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.
{{- if . }}
{{- if or .Version .Commit .Timestamp .ProjectCommit .ReplacedTemplates }}
#
# Provenance:
{{- if .Version }}
# - Version: {{ .Version }}
{{- end }}
{{- if .Commit }}
# - Generator Commit: {{ .Commit }}{{ if .Dirty }} (dirty){{ end }}
{{- end }}
{{- if .Timestamp }}
# - Generated: {{ .Timestamp }}
{{- end }}
{{- if .ProjectCommit }}
# - Project Commit: {{ .ProjectCommit }}{{ if .ProjectDirty }} (dirty){{ end }}
{{- end }}
{{- if .ReplacedTemplates }}
# - Templates: Replaced (ID: {{ .TemplateID }})
{{- else }}
# - Templates: Built-in
{{- end }}
{{- end }}
{{- end }}
{{- end -}}""",
    content
)

with open("templates/common/common.gotmpl", "w") as f:
    f.write(content)
