package go_subcommand

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/arran4/go-subcommand/model"
	"github.com/arran4/go-subcommand/parsers"
	_ "github.com/arran4/go-subcommand/parsers/commentv1"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

//go:embed templates
var TemplatesFS embed.FS

var templates *template.Template

// FileWriter interface allows mocking file system writes
type FileWriter interface {
	WriteFile(path string, content []byte, perm os.FileMode) error
	MkdirAll(path string, perm os.FileMode) error
	ReadFile(path string) ([]byte, error)
	ReadDir(path string) ([]fs.DirEntry, error)
}

// OSFileWriter implements FileWriter using os package
type OSFileWriter struct{}

func (w *OSFileWriter) WriteFile(path string, content []byte, perm os.FileMode) error {
	return os.WriteFile(path, content, perm)
}
func (w *OSFileWriter) MkdirAll(path string, perm os.FileMode) error {
	return os.MkdirAll(path, perm)
}
func (w *OSFileWriter) ReadFile(path string) ([]byte, error) {
	return os.ReadFile(path)
}
func (w *OSFileWriter) ReadDir(path string) ([]fs.DirEntry, error) {
	return os.ReadDir(path)
}

// CollectingFileWriter collects files and directories to be written
type CollectingFileWriter struct {
	Files map[string][]byte
	Dirs  map[string]bool
}

func NewCollectingFileWriter() *CollectingFileWriter {
	return &CollectingFileWriter{
		Files: make(map[string][]byte),
		Dirs:  make(map[string]bool),
	}
}

func (w *CollectingFileWriter) WriteFile(path string, content []byte, perm os.FileMode) error {
	w.Files[path] = content
	return nil
}

func (w *CollectingFileWriter) MkdirAll(path string, perm os.FileMode) error {
	w.Dirs[path] = true
	return nil
}

func (w *CollectingFileWriter) ReadFile(path string) ([]byte, error) {
	return nil, os.ErrNotExist
}

func (w *CollectingFileWriter) ReadDir(path string) ([]fs.DirEntry, error) {
	return nil, os.ErrNotExist
}

// Generate is a subcommand `gosubc generate` generates the subcommand code
//
// Flags:
//   dir:        --dir         (default: ".")         Project root directory containing go.mod
//   manDir:     --man-dir                            Directory to generate man pages in optional
//   parserName: --parser-name (default: "commentv1") Name of the parser to use
//   paths:      --path        (default: nil)         Paths to search for subcommands (relative to dir)
//   recursive:  --recursive   (default: true)        Search recursively
//   force:      --force       (default: false)       Force overwrite of files not generated by gosubc
func Generate(dir string, manDir string, parserName string, paths []string, recursive bool, force bool) error {
	if dir == "." {
		if _, err := os.Stat("go.mod"); os.IsNotExist(err) {
			if root, err := findModuleRoot("."); err == nil {
				dir = root
			}
		}
	}
	return GenerateWithFS(os.DirFS(dir), &OSFileWriter{}, dir, manDir, parserName, &parsers.ParseOptions{
		SearchPaths: paths,
		Recursive:   recursive,
	}, force)
}

func findModuleRoot(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(abs, "go.mod")); err == nil {
			return abs, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", fmt.Errorf("go.mod not found")
		}
		abs = parent
	}
}

// GenerateWithFS generates code using provided FS and Writer
func GenerateWithFS(inputFS fs.FS, writer FileWriter, dir string, manDir string, parserName string, options *parsers.ParseOptions, force bool) error {
	if err := initTemplates(); err != nil {
		return err
	}

	p, err := parsers.Get(parserName)
	if err != nil {
		return err
	}

	// inputFS is already rooted at the source directory, so we parse from "."
	dataModel, err := p.Parse(inputFS, ".", options)
	if err != nil {
		return err
	}
	if len(dataModel.Commands) == 0 {
		return fmt.Errorf("no commands found in %s", dir)
	}

	collector := NewCollectingFileWriter()

	for _, cmd := range dataModel.Commands {
		cmdOutDir := filepath.Join(dir, "cmd", cmd.MainCmdName)
		if err := generateFile(collector, cmdOutDir, "main.go", "main.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(collector, cmdOutDir, "root.go", "root.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(collector, filepath.Join(dir, "cmd"), "errors.go", "errors.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(collector, filepath.Join(dir, "cmd"), "agents.md", "agents.md.gotmpl", cmd, false); err != nil {
			return err
		}
		if err := generateFile(collector, cmdOutDir, "root_test.go", "root_test.go.gotmpl", cmd, true); err != nil {
			return err
		}
		cmdTemplatesDir := filepath.Join(cmdOutDir, "templates")
		if err := generateFile(collector, cmdTemplatesDir, "templates.go", "templates.go.gotmpl", cmd, true); err != nil {
			return err
		}
		for _, subCmd := range cmd.SubCommands {
			assignUsageFileNames(cmd.SubCommands)
			if err := generateSubCommandFiles(collector, cmdOutDir, cmdTemplatesDir, manDir, subCmd); err != nil {
				return err
			}
		}
	}

	for path, content := range collector.Files {
		existing, err := writer.ReadFile(path)
		if err == nil {
			if bytes.Equal(existing, content) {
				continue
			}
			if !force && !isGenerated(existing) {
				return fmt.Errorf("file %s exists and was not generated by gosubc (use --force to overwrite)", path)
			}
		}
	}

	if !force {
		touchedDirs := make(map[string]bool)
		for path := range collector.Files {
			touchedDirs[filepath.Dir(path)] = true
		}
		for dir := range collector.Dirs {
			touchedDirs[dir] = true
		}

		for dir := range touchedDirs {
			entries, err := writer.ReadDir(dir)
			if err == nil {
				for _, entry := range entries {
					if entry.IsDir() {
						continue
					}
					fullPath := filepath.Join(dir, entry.Name())
					if _, ok := collector.Files[fullPath]; !ok {
						return fmt.Errorf("file %s is present in the directory but not in the generated set (use --force to ignore)", fullPath)
					}
				}
			}
		}
	}

	for path, content := range collector.Files {
		if err := writer.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", filepath.Dir(path), err)
		}
		if err := writer.WriteFile(path, content, 0644); err != nil {
			return fmt.Errorf("failed to create file %s: %w", path, err)
		}
	}

	return nil
}

func isGenerated(content []byte) bool {
	s := string(content)
	markers := []string{
		"Code generated by github.com/arran4/go-subcommand/cmd/gosubc",
		"Generated by github.com/arran4/go-subcommand/cmd/gosubc",
	}
	for _, m := range markers {
		if strings.Contains(s, m) {
			return true
		}
	}
	return false
}
func assignUsageFileNames(subCommands []*model.SubCommand) {
	seen := make(map[string]int)
	for _, sc := range subCommands {
		lower := strings.ToLower(sc.SubCommandName)
		count := seen[lower]
		seen[lower]++
		suffix := ""
		if count > 0 {
			suffix = fmt.Sprintf("_%d", count)
		}
		sc.UsageFileName = fmt.Sprintf("%s%s_usage.txt", lower, suffix)

		if len(sc.SubCommands) > 0 {
			assignUsageFileNames(sc.SubCommands)
		}
	}
}
func generateSubCommandFiles(writer FileWriter, cmdOutDir, cmdTemplatesDir, manDir string, subCmd *model.SubCommand) error {
	if err := generateFile(writer, cmdOutDir, subCmd.SubCommandName+".go", "cmd.go.gotmpl", subCmd, true); err != nil {
		return err
	}
	if err := generateFile(writer, cmdOutDir, subCmd.SubCommandName+"_test.go", "cmd_test.go.gotmpl", subCmd, true); err != nil {
		return err
	}
	if err := generateFile(writer, cmdTemplatesDir, subCmd.UsageFileName, "usage.txt.gotmpl", subCmd, false); err != nil {
		return err
	}
	if manDir != "" {
		manFileName := fmt.Sprintf("%s-%s.1", subCmd.MainCmdName, strings.ReplaceAll(subCmd.SubCommandSequence(), " ", "-"))
		if err := generateFile(writer, manDir, manFileName, "man.gotmpl", subCmd, false); err != nil {
			return err
		}
	}
	for _, s := range subCmd.SubCommands {
		if err := generateSubCommandFiles(writer, cmdOutDir, cmdTemplatesDir, manDir, s); err != nil {
			return err
		}
	}
	return nil
}

// Helper to bridge legacy parse calls
func parse(dir string, parserName string, options *parsers.ParseOptions) (*model.DataModel, error) {
	if dir == "" {
		dir = "."
	}
	p, err := parsers.Get(parserName)
	if err != nil {
		return nil, err
	}
	return p.Parse(os.DirFS(dir), ".", options)
}
func initTemplates() error {
	var err error
	templates, err = ParseTemplates(TemplatesFS)
	return err
}

func ParseTemplates(fsys fs.FS) (*template.Template, error) {
	tmpl := template.New("").Funcs(template.FuncMap{
		"lower":   strings.ToLower,
		"title":   func(s string) string { return cases.Title(language.Und, cases.NoLower).String(s) },
		"upper":   strings.ToUpper,
		"replace": strings.ReplaceAll,
		"add":     func(a, b int) int { return a + b },
		"until": func(n int) []int {
			res := make([]int, n)
			for i := 0; i < n; i++ {
				res[i] = i
			}
			return res
		},
		"slice": func(args ...interface{}) []interface{} {
			return args
		},
	})

	var patterns []string
	err := fs.WalkDir(fsys, "templates", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".gotmpl") {
			patterns = append(patterns, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("error walking templates: %w", err)
	}

	if len(patterns) == 0 {
		return tmpl, nil
	}

	tmpl, err = tmpl.ParseFS(fsys, patterns...)
	if err != nil {
		return nil, fmt.Errorf("error parsing templates: %w", err)
	}
	return tmpl, nil
}
func generateFile(writer FileWriter, dir, fileName, templateName string, data interface{}, formatCode bool) error {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, templateName, data); err != nil {
		return fmt.Errorf("failed to execute template %s: %w", templateName, err)
	}

	var content []byte
	if formatCode {
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("failed to format generated code for %s: %w\n%s", fileName, err, buf.String())
		}
		content = formatted
	} else {
		content = buf.Bytes()
	}

	if err := writer.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Use filepath.Join for file paths as it is OS-aware, which is appropriate for FileWriter
	filePath := filepath.Join(dir, fileName)

	if err := writer.WriteFile(filePath, content, 0644); err != nil {
		return fmt.Errorf("failed to create file %s: %w", filePath, err)
	}
	return nil
}
