package go_subcommand

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/arran4/go-subcommand/model"
	"github.com/arran4/go-subcommand/parsers"
	_ "github.com/arran4/go-subcommand/parsers/commentv1"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

//go:embed templates
var TemplatesFS embed.FS

var templates *template.Template

// FileWriter interface allows mocking file system writes
type FileWriter interface {
	WriteFile(path string, content []byte, perm os.FileMode) error
	MkdirAll(path string, perm os.FileMode) error
}

// OSFileWriter implements FileWriter using os package
type OSFileWriter struct{}

func (w *OSFileWriter) WriteFile(path string, content []byte, perm os.FileMode) error {
	return os.WriteFile(path, content, perm)
}
func (w *OSFileWriter) MkdirAll(path string, perm os.FileMode) error {
	return os.MkdirAll(path, perm)
}

// Generate is a subcommand `gosubc generate` generates the subcommand code
//
// Flags:
//   dir:        --dir         (default: ".")         Project root directory containing go.mod
//   manDir:     --man-dir                            Directory to generate man pages in optional
//   parserName: --parser-name (default: "commentv1") Name of the parser to use
//   paths:      --path        (default: nil)         Paths to search for subcommands (relative to dir)
//   recursive:  --recursive   (default: true)        Search recursively
//   force:      --force       (default: false)       Overwrite files not generated by gosubc and ignore extraneous files
func Generate(dir string, manDir string, parserName string, paths []string, recursive bool, force bool) error {
	return GenerateWithFS(os.DirFS(dir), &OSFileWriter{}, dir, manDir, parserName, &parsers.ParseOptions{
		SearchPaths: paths,
		Recursive:   recursive,
	}, force)
}

// GenerateWithFS generates code using provided FS and Writer
func GenerateWithFS(inputFS fs.FS, writer FileWriter, dir string, manDir string, parserName string, options *parsers.ParseOptions, force bool) error {
	if err := initTemplates(); err != nil {
		return err
	}

	p, err := parsers.Get(parserName)
	if err != nil {
		return err
	}

	// inputFS is already rooted at the source directory, so we parse from "."
	dataModel, err := p.Parse(inputFS, ".", options)
	if err != nil {
		return err
	}
	if len(dataModel.Commands) == 0 {
		return fmt.Errorf("no commands found in %s", dir)
	}

	// Pre-process commands to assign usage file names uniquely
	for _, cmd := range dataModel.Commands {
		assignUsageFileNames(cmd.SubCommands)
	}

	// Generate content to memory buffer
	buffer := &BufferFileWriter{
		Files: make(map[string][]byte),
	}
	if err := generateFiles(buffer, dataModel, dir, manDir); err != nil {
		return err
	}

	// Validate output directory against expected files
	var expectedFiles []string
	for path := range buffer.Files {
		expectedFiles = append(expectedFiles, path)
	}
	if err := validateFiles(expectedFiles, force); err != nil {
		return err
	}

	// Write buffered content to actual writer
	for path, content := range buffer.Files {
		// Use filepath.Split to separate dir and filename
		d, _ := filepath.Split(path)
		if err := writer.MkdirAll(d, 0755); err != nil {
			return err
		}
		if err := writer.WriteFile(path, content, 0644); err != nil {
			return err
		}
	}
	return nil
}

func generateFiles(writer FileWriter, dataModel *model.DataModel, dir, manDir string) error {
	for _, cmd := range dataModel.Commands {
		cmdOutDir := path.Join(dir, "cmd", cmd.MainCmdName)
		if err := generateFile(writer, cmdOutDir, "main.go", "main.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(writer, cmdOutDir, "root.go", "root.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(writer, path.Join(dir, "cmd"), "errors.go", "errors.go.gotmpl", cmd, true); err != nil {
			return err
		}
		if err := generateFile(writer, path.Join(dir, "cmd"), "agents.md", "agents.md.gotmpl", cmd, false); err != nil {
			return err
		}
		if err := generateFile(writer, cmdOutDir, "root_test.go", "root_test.go.gotmpl", cmd, true); err != nil {
			return err
		}
		cmdTemplatesDir := path.Join(cmdOutDir, "templates")
		if err := generateFile(writer, cmdTemplatesDir, "templates.go", "templates.go.gotmpl", cmd, true); err != nil {
			return err
		}
		for _, subCmd := range cmd.SubCommands {
			// assignUsageFileNames is already done
			if err := generateSubCommandFiles(writer, cmdOutDir, cmdTemplatesDir, manDir, subCmd); err != nil {
				return err
			}
		}
	}
	return nil
}

func assignUsageFileNames(subCommands []*model.SubCommand) {
	seen := make(map[string]int)
	for _, sc := range subCommands {
		lower := strings.ToLower(sc.SubCommandName)
		count := seen[lower]
		seen[lower]++
		suffix := ""
		if count > 0 {
			suffix = fmt.Sprintf("_%d", count)
		}
		sc.UsageFileName = fmt.Sprintf("%s%s_usage.txt", lower, suffix)

		if len(sc.SubCommands) > 0 {
			assignUsageFileNames(sc.SubCommands)
		}
	}
}
func generateSubCommandFiles(writer FileWriter, cmdOutDir, cmdTemplatesDir, manDir string, subCmd *model.SubCommand) error {
	if err := generateFile(writer, cmdOutDir, subCmd.SubCommandName+".go", "cmd.go.gotmpl", subCmd, true); err != nil {
		return err
	}
	if err := generateFile(writer, cmdOutDir, subCmd.SubCommandName+"_test.go", "cmd_test.go.gotmpl", subCmd, true); err != nil {
		return err
	}
	if err := generateFile(writer, cmdTemplatesDir, subCmd.UsageFileName, "usage.txt.gotmpl", subCmd, false); err != nil {
		return err
	}
	if manDir != "" {
		manFileName := fmt.Sprintf("%s-%s.1", subCmd.MainCmdName, strings.ReplaceAll(subCmd.SubCommandSequence(), " ", "-"))
		if err := generateFile(writer, manDir, manFileName, "man.gotmpl", subCmd, false); err != nil {
			return err
		}
	}
	for _, s := range subCmd.SubCommands {
		if err := generateSubCommandFiles(writer, cmdOutDir, cmdTemplatesDir, manDir, s); err != nil {
			return err
		}
	}
	return nil
}

// Helper to bridge legacy parse calls
func parse(dir string, parserName string, options *parsers.ParseOptions) (*model.DataModel, error) {
	if dir == "" {
		dir = "."
	}
	p, err := parsers.Get(parserName)
	if err != nil {
		return nil, err
	}
	return p.Parse(os.DirFS(dir), ".", options)
}
func initTemplates() error {
	var err error
	templates, err = ParseTemplates(TemplatesFS)
	return err
}

func ParseTemplates(fsys fs.FS) (*template.Template, error) {
	tmpl := template.New("").Funcs(template.FuncMap{
		"lower":   strings.ToLower,
		"title":   func(s string) string { return cases.Title(language.Und, cases.NoLower).String(s) },
		"upper":   strings.ToUpper,
		"replace": strings.ReplaceAll,
		"add":     func(a, b int) int { return a + b },
		"until": func(n int) []int {
			res := make([]int, n)
			for i := 0; i < n; i++ {
				res[i] = i
			}
			return res
		},
		"slice": func(args ...interface{}) []interface{} {
			return args
		},
	})

	var patterns []string
	err := fs.WalkDir(fsys, "templates", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".gotmpl") {
			patterns = append(patterns, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("error walking templates: %w", err)
	}

	if len(patterns) == 0 {
		return tmpl, nil
	}

	tmpl, err = tmpl.ParseFS(fsys, patterns...)
	if err != nil {
		return nil, fmt.Errorf("error parsing templates: %w", err)
	}
	return tmpl, nil
}
func generateFile(writer FileWriter, dir, fileName, templateName string, data interface{}, formatCode bool) error {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, templateName, data); err != nil {
		return fmt.Errorf("failed to execute template %s: %w", templateName, err)
	}

	var content []byte
	if formatCode {
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("failed to format generated code for %s: %w\n%s", fileName, err, buf.String())
		}
		content = formatted
	} else {
		content = buf.Bytes()
	}

	if err := writer.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Use filepath.Join for file paths as it is OS-aware, which is appropriate for FileWriter
	filePath := filepath.Join(dir, fileName)

	if err := writer.WriteFile(filePath, content, 0644); err != nil {
		return fmt.Errorf("failed to create file %s: %w", filePath, err)
	}
	return nil
}

type BufferFileWriter struct {
	Files map[string][]byte
}

func (w *BufferFileWriter) WriteFile(path string, content []byte, perm os.FileMode) error {
	w.Files[path] = content
	return nil
}

func (w *BufferFileWriter) MkdirAll(path string, perm os.FileMode) error {
	return nil
}

func validateFiles(expectedFiles []string, force bool) error {
	if force {
		return nil
	}

	expectedSet := make(map[string]bool)
	relevantDirs := make(map[string]bool)

	for _, p := range expectedFiles {
		p = filepath.Clean(p)
		expectedSet[p] = true
		// Mark directory as relevant
		dir := filepath.Dir(p)
		relevantDirs[dir] = true
	}

	// 1. Check for overwrite of non-generated files
	headerSnippet := "Generated by github.com/arran4/go-subcommand"

	for _, p := range expectedFiles {
		p = filepath.Clean(p)
		info, err := os.Stat(p)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return fmt.Errorf("error checking file %s: %w", p, err)
		}
		if info.IsDir() {
			continue // Should not happen for file paths
		}

		content, err := os.ReadFile(p)
		if err != nil {
			return fmt.Errorf("error reading file %s: %w", p, err)
		}

		// Check first 1KB or so
		checkLen := 1024
		if len(content) < checkLen {
			checkLen = len(content)
		}
		if !strings.Contains(strings.ToLower(string(content[:checkLen])), strings.ToLower(headerSnippet)) {
			return fmt.Errorf("attempting to overwrite non-generated file %s. Use --force to override", p)
		}
	}

	// 2. Check for extraneous files in relevant directories
	for dir := range relevantDirs {
		entries, err := os.ReadDir(dir)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return fmt.Errorf("error reading directory %s: %w", dir, err)
		}

		for _, entry := range entries {
			fullPath := filepath.Join(dir, entry.Name())

			if entry.IsDir() {
				// For directory, check if it's a parent of any expected file
				isParent := false
				for expected := range expectedSet {
					if strings.HasPrefix(expected, fullPath+string(os.PathSeparator)) {
						isParent = true
						break
					}
				}
				if !isParent {
					return fmt.Errorf("extraneous directory %s found in generated directory. Use --force to ignore", fullPath)
				}
			} else {
				// For file, check if it's in expected set
				if !expectedSet[fullPath] {
					return fmt.Errorf("extraneous file %s found in generated directory. Use --force to ignore", fullPath)
				}
			}
		}
	}

	return nil
}
