#!/bin/bash
set -e

# Create a temporary directory
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "Using temp dir: $TEMP_DIR"

# Define module name
MODULE_NAME="example.com/forcecheck"

# Create go.mod
cat <<EOF > "$TEMP_DIR/go.mod"
module $MODULE_NAME

go 1.25
EOF

# Create pkg directory
mkdir -p "$TEMP_DIR/pkg"

# Create lib.go with the subcommand definition
cat <<EOF > "$TEMP_DIR/pkg/lib.go"
package pkg

import "fmt"

// Run is a subcommand \`testapp run\`
func Run() {
	fmt.Println("Running...")
}
EOF

# Build gosubc
go build -o "$TEMP_DIR/gosubc" ./cmd/gosubc
GOSUBC_CMD="$TEMP_DIR/gosubc"

echo "Using gosubc: $GOSUBC_CMD"

# 1. Clean generation
echo "Test 1: Clean generation..."
(cd "$TEMP_DIR" && $GOSUBC_CMD generate)
echo "Test 1 Passed."

# 2. Add extraneous file -> Fail
echo "Test 2: Extraneous file check (should fail)..."
touch "$TEMP_DIR/cmd/testapp/extra.txt"
OUTPUT=$((cd "$TEMP_DIR" && $GOSUBC_CMD generate) 2>&1 || true)
if echo "$OUTPUT" | grep -q "extraneous file"; then
    echo "Test 2 Passed (failed as expected with correct error)."
else
    echo "Test 2 Failed: Expected failure due to extraneous file."
    echo "Got: $OUTPUT"
    exit 1
fi

# 3. Add extraneous file + --force -> Success
echo "Test 3: Extraneous file + --force (should succeed)..."
if (cd "$TEMP_DIR" && $GOSUBC_CMD generate --force); then
    echo "Test 3 Passed."
else
    echo "Test 3 Failed: Expected success with --force."
    exit 1
fi

# Clean up extraneous file for next test
rm "$TEMP_DIR/cmd/testapp/extra.txt"

# 4. Modify generated file (remove header) -> Fail
echo "Test 4: Modified generated file (header check) (should fail)..."
# Overwrite main.go with no header
cat <<EOF > "$TEMP_DIR/cmd/testapp/main.go"
package main
func main() {}
EOF

if (cd "$TEMP_DIR" && $GOSUBC_CMD generate 2>/dev/null); then
    echo "Test 4 Failed: Expected failure due to modified file (missing header)."
    exit 1
else
    echo "Test 4 Passed (failed as expected)."
fi

# 5. Modify generated file + --force -> Success
echo "Test 5: Modified generated file + --force (should succeed)..."
if (cd "$TEMP_DIR" && $GOSUBC_CMD generate --force); then
    echo "Test 5 Passed."
else
    echo "Test 5 Failed: Expected success with --force."
    exit 1
fi

# Verify header is back
if grep -i -q "Generated by github.com/arran4/go-subcommand" "$TEMP_DIR/cmd/testapp/main.go"; then
    echo "Header verified."
else
    echo "Test 5 Failed: Header not restored."
    exit 1
fi

echo "All force flag tests passed."
