#!/bin/bash
set -e

# Create a temporary directory
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "Using temp dir: $TEMP_DIR"

# Define module name
MODULE_NAME="example.com/forcecheck"

# Create go.mod
cat <<EOF > "$TEMP_DIR/go.mod"
module $MODULE_NAME

go 1.25
EOF

# Create pkg directory
mkdir -p "$TEMP_DIR/pkg"

# Create lib.go with a simple subcommand definition
cat <<EOF > "$TEMP_DIR/pkg/lib.go"
package pkg

// Run is a subcommand \`testapp run\`
func Run() {}
EOF

# Function to run generate
run_generate() {
    local force_flag=$1
    echo "Running generate with force_flag='$force_flag'..."
    if command -v gosubc &> /dev/null; then
        gosubc generate --dir "$TEMP_DIR" $force_flag
    else
        # Fallback to running from source
        if [ -f "./go.mod" ]; then
             go run ./cmd/gosubc generate --dir "$TEMP_DIR" $force_flag
        else
            echo "Error: gosubc not found and not in repo root."
            exit 1
        fi
    fi
}

# 1. Initial Generation (Clean slate)
echo "--- Step 1: Initial Generation ---"
if ! run_generate ""; then
    echo "Initial generation failed!"
    exit 1
fi
echo "Initial generation successful."

# 2. Modify a generated file (remove header) to simulate non-generated file
GENERATED_FILE="$TEMP_DIR/cmd/testapp/run.go"
if [ ! -f "$GENERATED_FILE" ]; then
    echo "Generated file $GENERATED_FILE not found!"
    exit 1
fi

# Overwrite with content without header
cat <<EOF > "$GENERATED_FILE"
package main
// Manual file
func manual() {}
EOF

# 3. Run generate again without -f -> Should Fail
echo "--- Step 3: Run without -f (Expect Failure) ---"
if run_generate ""; then
    echo "Error: Generation succeeded but should have failed due to overwrite check!"
    exit 1
else
    echo "Generation failed as expected."
fi

# 4. Run generate again with --force -> Should Succeed
echo "--- Step 4: Run with --force (Expect Success) ---"
if ! run_generate "--force"; then
    echo "Error: Generation failed with --force!"
    exit 1
fi
echo "Generation with --force successful."

# Verify file was overwritten (should have header now)
if ! grep -q "Code generated by" "$GENERATED_FILE"; then
    echo "Error: File was not overwritten or header missing!"
    exit 1
fi

# 5. Add extraneous file to output directory
EXTRANEOUS_FILE="$TEMP_DIR/cmd/testapp/extraneous.txt"
echo "I should not be here" > "$EXTRANEOUS_FILE"

# 6. Run generate without -f -> Should Fail (extraneous file)
echo "--- Step 6: Run without -f (Expect Failure due to extraneous file) ---"
if run_generate ""; then
    echo "Error: Generation succeeded but should have failed due to extraneous file!"
    exit 1
else
    echo "Generation failed as expected (extraneous file)."
fi

# 7. Run generate with --force -> Should Succeed (extraneous file ignored)
echo "--- Step 7: Run with --force (Expect Success) ---"
if ! run_generate "--force"; then
    echo "Error: Generation failed with --force (extraneous file present)!"
    exit 1
fi
echo "Generation with --force successful."

echo "All force flag tests passed."
