// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/basic1"
)

var _ Cmd = (*Example1)(nil)

type Example1 struct {
	*RootCmd
	Flags       *flag.FlagSet
	SubCommands map[string]Cmd
}

func (c *Example1) Usage() {
	err := executeUsage(os.Stderr, "example1_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Example1) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Flags.Args()
	// Avoid unused variable warning
	if len(remainingArgs) == 0 {
		_ = remainingArgs
	}

	basic1.ExampleCmd1()

	return nil
}

func (c *RootCmd) NewExample1() *Example1 {
	set := flag.NewFlagSet("example1", flag.ContinueOnError)
	v := &Example1{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}
	set.Usage = v.Usage

	return v
}
