// Code generated by github.com/arran4/go-subcommand. DO NOT EDIT.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/arran4/go-subcommand/examples/basic1"
)

var _ Cmd = (*RootCmd)(nil)

type ExampleCmd1Cmd struct {
	*RootCmd
	Flags *flag.FlagSet
}

func (c *ExampleCmd1Cmd) Usage() {
	err := executeUsage(os.Stderr, "exampleCmd1_usage.txt", c)
	if err != nil {
		log.Panicf("Error generating usage: %s", err)
	}
}

func (c *ExampleCmd1Cmd) Execute(args []string) error {
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	basic1.ExampleCmd1()
	return nil
}

func (c *RootCmd) NewExampleCmd1Cmd() *ExampleCmd1Cmd {
	set := flag.NewFlagSet("exampleCmd1", flag.ContinueOnError)
	v := &ExampleCmd1Cmd{
		RootCmd: c,
		Flags:   set,
	}
	set.Usage = v.Usage
	return v
}
