// Code generated by github.com/arran4/go-subcommand. DO NOT EDIT.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
)

var _ Cmd = (*RootCmd)(nil)

// RootCmd is the top-level command state.
type RootCmd struct {
	Flags    *flag.FlagSet
	Version  string
	Commit   string
	Date     string
	ProgName string
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "root_usage.txt", c)
	if err != nil {
		log.Panicf("Error generating usage: %s", err)
	}
}

func NewRoot(progName string, version string, commit string, date string) (*RootCmd, error) {
	fs := flag.NewFlagSet("", flag.ContinueOnError)
	rc := &RootCmd{
		Flags:    fs,
		Version:  version,
		Commit:   commit,
		Date:     date,
		ProgName: progName,
	}
	fs.Usage = rc.Usage
	return rc, nil
}

func (c *RootCmd) Execute(args []string) error {
	if len(args) == 0 {
		c.Usage()
		return nil
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	switch args[0] {
	case "version":
		cmd := c.NewVersionCmd()
		if err := cmd.Execute(c.Flags.Args()); err != nil {
			return fmt.Errorf("version: %w", err)
		}
		return nil
	default:
		c.Usage()
		return NewUserError(nil, fmt.Sprintf("Unknown flag: %s", args[0]))
	}
}
