// Code generated by github.com/arran4/go-subcommand. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
)

var _ Cmd = (*VersionCmd)(nil)

type VersionCmd struct {
	*RootCmd
	Flags *flag.FlagSet

	SubCommands map[string]Cmd
}

func (c *VersionCmd) Usage() {
	err := executeUsage(os.Stderr, "version_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *VersionCmd) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	fmt.Printf("Version: %s\n", c.Version)

	return nil
}

func (c *RootCmd) NewVersionCmd() *VersionCmd {
	set := flag.NewFlagSet("version", flag.ContinueOnError)
	v := &VersionCmd{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.Usage = v.Usage

	return v
}
