// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strings"

	"github.com/arran4/go-subcommand/examples/issue185/app"
	"github.com/arran4/go-subcommand/examples/issue185/cmd"
)

var _ Cmd = (*Mycmd2)(nil)

type Mycmd2 struct {
	*RootCmd
	Flags         *flag.FlagSet
	reader        io.Reader
	writer        io.Writer
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Mycmd2) error
}

type UsageDataMycmd2 struct {
	*Mycmd2
	Recursive bool
}

func (c *Mycmd2) Usage() {
	err := executeUsage(os.Stderr, "mycmd2_usage.txt", UsageDataMycmd2{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Mycmd2) UsageRecursive() {
	err := executeUsage(os.Stderr, "mycmd2_usage.txt", UsageDataMycmd2{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Mycmd2) Execute(args []string) (err error) {
	var cleanups []func() error
	defer func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			if cerr := cleanups[i](); cerr != nil && err == nil {
				err = cerr
			}
		}
	}()
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "writer":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				if value == "-" {
					c.writer = os.Stdout
				} else {
					f, err := generatedOpenWriter(value)
					if err != nil {
						return err
					}
					cleanups = append(cleanups, f.Close)
					c.writer = f
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	// Handle positional argument reader
	{
		argIndex := 1
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			if argVal == "-" {
				c.reader = os.Stdin
			} else {
				f, err := generatedOpenReader(argVal)
				if err != nil {
					return err
				}
				cleanups = append(cleanups, f.Close)
				c.reader = f
			}
		} else {
			if "-" == "-" {
				c.reader = os.Stdin
			} else {
				f, err := generatedOpenReader("-")
				if err != nil {
					return err
				}
				cleanups = append(cleanups, f.Close)
				c.reader = f
			}
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("mycmd2 failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewMycmd2() *Mycmd2 {
	set := flag.NewFlagSet("mycmd2", flag.ContinueOnError)
	v := &Mycmd2{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.Func("writer", "TODO: Add usage text", func(s string) error {
		// Parsed manually in Execute
		return nil
	})
	set.Usage = v.Usage

	v.CommandAction = func(c *Mycmd2) error {

		err := app.MyCmd2(c.reader, c.writer)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("mycmd2 failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
