// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/arran4/go-subcommand/examples/flags"
)

var _ Cmd = (*flagsCmd)(nil)

type flagsCmd struct {
	*RootCmd
	Flags *flag.FlagSet

	name string

	age int

	verbose bool

	timeout time.Duration

	SubCommands map[string]Cmd
}

func (c *flagsCmd) Usage() {
	err := executeUsage(os.Stderr, "flags_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *flagsCmd) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	main.MyCommand(c.name, c.age, c.verbose, c.timeout)

	return nil
}

func (c *RootCmd) NewflagsCmd() *flagsCmd {
	set := flag.NewFlagSet("flags", flag.ContinueOnError)
	v := &flagsCmd{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.name, "n", "World", "Your name")
	set.StringVar(&v.name, "name", "World", "Your name")

	set.IntVar(&v.age, "a", 18, "Your age")

	set.BoolVar(&v.verbose, "v", false, "Verbose mode")

	if d, err := time.ParseDuration("10s"); err == nil {
		set.DurationVar(&v.timeout, "t", d, "Timeout duration")
	} else {
		set.DurationVar(&v.timeout, "t", 0, "Timeout duration")
	}

	set.Usage = v.Usage

	return v
}
