// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Another)(nil)

type Another struct {
	*RootCmd
	Flags       *flag.FlagSet
	wait        time.Duration
	SubCommands map[string]Cmd
}

func (c *Another) Usage() {
	err := executeUsage(os.Stderr, "another_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Another) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "wait", "w":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				d, err := time.ParseDuration(value)
				if err != nil {
					return fmt.Errorf("invalid duration value for flag %s: %s", name, value)
				}
				c.wait = d
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}

	complex.Another(c.wait)

	return nil
}

func (c *RootCmd) NewAnother() *Another {
	set := flag.NewFlagSet("another", flag.ContinueOnError)
	v := &Another{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "wait", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "wait", 0, "How long to wait")
	}
	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "w", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "w", 0, "How long to wait")
	}
	set.Usage = v.Usage

	return v
}
