// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
	"time"
)

func TestAnother_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewAnother()

	called := false
	cmd.CommandAction = func(c *Another) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--wait")
	args = append(args, "1s")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.wait != 1*time.Second {
		t.Errorf("Expected wait to be 1s, got '%v'", cmd.wait)
	}
}
