// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Another)(nil)

type Another struct {
	*RootCmd
	Flags         *flag.FlagSet
	wait          time.Duration
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Another) error
}

type UsageDataAnother struct {
	*Another
	Recursive bool
}

func (c *Another) Usage() {
	err := executeUsage(os.Stderr, "another_usage.txt", UsageDataAnother{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Another) UsageRecursive() {
	err := executeUsage(os.Stderr, "another_usage.txt", UsageDataAnother{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Another) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "wait":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := time.ParseDuration(value)
				if err != nil {
					return fmt.Errorf("invalid duration value for flag %s: %s", name, value)
				}
				c.wait = v
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "w" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					v, err := time.ParseDuration(value)
					if err != nil {
						return fmt.Errorf("invalid duration value for flag -%s: %s", char, value)
					}
					c.wait = v
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("another failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewAnother() *Another {
	set := flag.NewFlagSet("another", flag.ContinueOnError)
	v := &Another{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "wait", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "wait", 0, "How long to wait")
	}
	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "w", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "w", 0, "How long to wait")
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *Another) error {

		complex.Another(c.wait)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
