// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Another)(nil)

type Another struct {
	*RootCmd
	Flags       *flag.FlagSet
	wait        time.Duration
	SubCommands map[string]Cmd
}

func (c *Another) Usage() {
	err := executeUsage(os.Stderr, "another_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Another) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	complex.Another(c.wait)

	return nil
}

func (c *RootCmd) NewAnother() *Another {
	set := flag.NewFlagSet("another", flag.ContinueOnError)
	v := &Another{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "wait", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "wait", 0, "How long to wait")
	}
	if d, err := time.ParseDuration("1s"); err == nil {
		set.DurationVar(&v.wait, "w", d, "How long to wait")
	} else {
		set.DurationVar(&v.wait, "w", 0, "How long to wait")
	}
	set.Usage = v.Usage

	return v
}
