// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Nested)(nil)

type Nested struct {
	*Toplevel
	Flags       *flag.FlagSet
	count       int
	verbose     bool
	SubCommands map[string]Cmd
}

func (c *Nested) Usage() {
	err := executeUsage(os.Stderr, "nested_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Nested) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	complex.Nested(c.count, c.verbose)

	return nil
}

func (c *Toplevel) NewNested() *Nested {
	set := flag.NewFlagSet("nested", flag.ContinueOnError)
	v := &Nested{
		Toplevel:    c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.count, "count", 1, "Number of times to repeat")
	set.IntVar(&v.count, "c", 1, "Number of times to repeat")

	set.BoolVar(&v.verbose, "verbose", false, "Enable verbose output")
	set.BoolVar(&v.verbose, "v", false, "Enable verbose output")
	set.Usage = v.Usage

	return v
}
