// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Nested)(nil)

type Nested struct {
	*Toplevel
	Flags       *flag.FlagSet
	count       int
	verbose     bool
	SubCommands map[string]Cmd
}

type UsageDataNested struct {
	*Nested
	Recursive bool
}

func (c *Nested) Usage() {
	err := executeUsage(os.Stderr, "nested_usage.txt", UsageDataNested{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Nested) UsageRecursive() {
	err := executeUsage(os.Stderr, "nested_usage.txt", UsageDataNested{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Nested) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "count", "c":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.count = iv

			case "verbose", "v":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.verbose = b
				} else {
					c.verbose = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	complex.Nested(c.count, c.verbose)

	return nil
}

func (c *Toplevel) NewNested() *Nested {
	set := flag.NewFlagSet("nested", flag.ContinueOnError)
	v := &Nested{
		Toplevel:    c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.count, "c", 1, "Number of times to repeat")
	set.IntVar(&v.count, "count", 1, "Number of times to repeat")

	set.BoolVar(&v.verbose, "v", false, "Enable verbose output")
	set.BoolVar(&v.verbose, "verbose", false, "Enable verbose output")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
