// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*Toplevel)(nil)

type Toplevel struct {
	*RootCmd
	Flags       *flag.FlagSet
	name        string
	SubCommands map[string]Cmd
}

func (c *Toplevel) Usage() {
	err := executeUsage(os.Stderr, "toplevel_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Toplevel) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Flags.Args()
	// Avoid unused variable warning
	if len(remainingArgs) == 0 {
		_ = remainingArgs
	}

	complex.TopLevel(c.name)

	return nil
}

func (c *RootCmd) NewToplevel() *Toplevel {
	set := flag.NewFlagSet("toplevel", flag.ContinueOnError)
	v := &Toplevel{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.name, "name", "world", "The name to greet")
	set.StringVar(&v.name, "n", "world", "The name to greet")
	set.Usage = v.Usage

	v.SubCommands["nested"] = v.NewNested()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
