// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestToplevel_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewToplevel()

	called := false
	cmd.CommandAction = func(c *Toplevel) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--name")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.name != "test" {
		t.Errorf("Expected name to be 'test', got '%v'", cmd.name)
	}
}
