// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestToplevelNested_Execute(t *testing.T) {

	parent := &Toplevel{}
	cmd := parent.NewToplevelNested()

	called := false
	cmd.CommandAction = func(c *ToplevelNested) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--count")
	args = append(args, "1")
	args = append(args, "--verbose")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.count != 1 {
		t.Errorf("Expected count to be 1, got '%v'", cmd.count)
	}
	if cmd.verbose != true {
		t.Errorf("Expected verbose to be true, got '%v'", cmd.verbose)
	}
}
