// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/arran4/go-subcommand/examples/complex"
)

var _ Cmd = (*ToplevelNested)(nil)

type ToplevelNested struct {
	*Toplevel
	Flags         *flag.FlagSet
	count         int
	verbose       bool
	SubCommands   map[string]func() Cmd
	CommandAction func(c *ToplevelNested) error
}

type UsageDataToplevelNested struct {
	*ToplevelNested
	Recursive bool
}

func (c *ToplevelNested) Usage() {
	err := executeUsage(os.Stderr, "nested_usage.txt", UsageDataToplevelNested{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ToplevelNested) UsageRecursive() {
	err := executeUsage(os.Stderr, "nested_usage.txt", UsageDataToplevelNested{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *ToplevelNested) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "count":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.count = v

			case "verbose":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.verbose = b
				} else {
					c.verbose = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "c" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					v, err := strconv.Atoi(value)
					if err != nil {
						return fmt.Errorf("invalid integer value for flag -%s: %s", char, value)
					}
					c.count = v
				}

				if char == "v" {
					found = true
					c.verbose = true
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("nested failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Toplevel) NewToplevelNested() *ToplevelNested {
	set := flag.NewFlagSet("nested", flag.ContinueOnError)
	v := &ToplevelNested{
		Toplevel:    c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.IntVar(&v.count, "count", 1, "Number of times to repeat")
	set.IntVar(&v.count, "c", 1, "Number of times to repeat")

	set.BoolVar(&v.verbose, "verbose", false, "Enable verbose output")
	set.BoolVar(&v.verbose, "v", false, "Enable verbose output")
	set.Usage = v.Usage

	v.CommandAction = func(c *ToplevelNested) error {

		complex.Nested(c.count, c.verbose)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
