// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/issue50"
)

var _ Cmd = (*Child)(nil)

type Child struct {
	*Parent
	Flags       *flag.FlagSet
	verbose     bool
	SubCommands map[string]Cmd
}

func (c *Child) Usage() {
	err := executeUsage(os.Stderr, "child_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Child) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Flags.Args()

	if err := issue50.Child(c.verbose); err != nil {
		return fmt.Errorf("child failed: %w", err)
	}

	return nil
}

func (c *Parent) NewChild() *Child {
	set := flag.NewFlagSet("child", flag.ContinueOnError)
	v := &Child{
		Parent:      c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.verbose, "verbose", false, "TODO: Add usage text")
	set.Usage = v.Usage

	return v
}
