// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestChild_Execute(t *testing.T) {

	parent := &Parent{}
	cmd := parent.NewChild()

	called := false
	cmd.CommandAction = func(c *Child) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--verbose")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.verbose != true {
		t.Errorf("Expected verbose to be true, got '%v'", cmd.verbose)
	}
}
