// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/issue50"
)

var _ Cmd = (*Parent)(nil)

type Parent struct {
	*RootCmd
	Flags       *flag.FlagSet
	verbose     bool
	SubCommands map[string]Cmd
}

func (c *Parent) Usage() {
	err := executeUsage(os.Stderr, "parent_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Parent) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Flags.Args()

	if err := issue50.Parent(c.verbose); err != nil {
		return fmt.Errorf("parent failed: %w", err)
	}

	return nil
}

func (c *RootCmd) NewParent() *Parent {
	set := flag.NewFlagSet("parent", flag.ContinueOnError)
	v := &Parent{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.verbose, "verbose", false, "TODO: Add usage text")
	set.Usage = v.Usage

	v.SubCommands["child"] = v.NewChild()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
