// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/stringdiff"
)

var _ Cmd = (*Diff)(nil)

type Diff struct {
	*RootCmd
	Flags       *flag.FlagSet
	file1       string
	file2       string
	maxLines    int
	term        bool
	interactive bool
	SubCommands map[string]Cmd
}

type UsageDataDiff struct {
	*Diff
	Recursive bool
}

func (c *Diff) Usage() {
	err := executeUsage(os.Stderr, "diff_usage.txt", UsageDataDiff{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Diff) UsageRecursive() {
	err := executeUsage(os.Stderr, "diff_usage.txt", UsageDataDiff{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Diff) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "maxLines", "max-lines", "m":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.maxLines = iv

			case "term", "t":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.term = b
				} else {
					c.term = true
				}

			case "interactive", "i":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.interactive = b
				} else {
					c.interactive = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	if len(remainingArgs) < 2 {
		return fmt.Errorf("expected at least 2 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument file1
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.file1 = argVal
		}
	}
	// Handle positional argument file2
	{
		argIndex := 1
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.file2 = argVal
		}
	}

	if err := stringdiff.RunDiff(c.file1, c.file2, c.maxLines, c.term, c.interactive); err != nil {
		return fmt.Errorf("diff failed: %w", err)
	}

	return nil
}

func (c *RootCmd) NewDiff() *Diff {
	set := flag.NewFlagSet("diff", flag.ContinueOnError)
	v := &Diff{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.maxLines, "max-lines", 1000, "Max lines to lookahead for alignment")
	set.IntVar(&v.maxLines, "m", 1000, "Max lines to lookahead for alignment")

	set.BoolVar(&v.term, "term", false, "Enable terminal colors")
	set.BoolVar(&v.term, "t", false, "Enable terminal colors")

	set.BoolVar(&v.interactive, "interactive", false, "Enable interactive mode todo")
	set.BoolVar(&v.interactive, "i", false, "Enable interactive mode todo")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
