// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/arran4/go-subcommand/examples/gnu-root-goflag-child/cmd"
	"github.com/arran4/go-subcommand/examples/gnu-root-goflag-child/internal/myapp"
)

var _ Cmd = (*Child)(nil)

type Child struct {
	*RootCmd
	Flags         *flag.FlagSet
	goFlag        string
	boolFlag      bool
	args          []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Child) error
}

type UsageDataChild struct {
	*Child
	Recursive bool
}

func (c *Child) Usage() {
	err := executeUsage(os.Stderr, "child_usage.txt", UsageDataChild{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Child) UsageRecursive() {
	err := executeUsage(os.Stderr, "child_usage.txt", UsageDataChild{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Child) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg[1:]
			if strings.HasPrefix(name, "-") {
				name = name[1:]
			}
			if name == "help" || name == "h" {
				c.Usage()
				return nil
			}

			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}

			_ = value
			_ = hasValue

			found := false
			switch name {

			case "goFlag", "go-flag":
				found = true
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.goFlag = value

			case "boolFlag", "b":
				found = true
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.boolFlag = b
				} else {
					c.boolFlag = true
				}

			case "args":
				found = true
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.args = append(c.args, value)
			default:
				// Try to see if it's a combined boolean short flag, only if single dash was used.
				// Actually, go-flag doesn't do GNU-style short flag clustering. It just looks for the exact name.
				// If not found, it's an error.
			}

			if !found {
				return fmt.Errorf("unknown flag: -%s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("child failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewChild() *Child {
	set := flag.NewFlagSet("child", flag.ContinueOnError)
	v := &Child{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.goFlag, "go-flag", "flag", "TODO: Add usage text")

	set.BoolVar(&v.boolFlag, "b", false, "TODO: Add usage text")

	set.Var((*StringSlice)(&v.args), "args", "(positional: true)")
	set.Usage = v.Usage

	v.CommandAction = func(c *Child) error {

		err := myapp.Child(c.goFlag, c.boolFlag, c.args)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("child failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
