// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"slices"

	"github.com/arran4/go-subcommand/examples/gnu-root-goflag-child/cmd"
	"github.com/arran4/go-subcommand/examples/gnu-root-goflag-child/internal/myapp"
)

var _ Cmd = (*Child)(nil)

type Child struct {
	*RootCmd
	Flags         *flag.FlagSet
	goFlag        string
	boolFlag      bool
	args          []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Child) error
}

type UsageDataChild struct {
	*Child
	Recursive bool
}

func (c *Child) Usage() {
	err := executeUsage(os.Stderr, "child_usage.txt", UsageDataChild{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Child) UsageRecursive() {
	err := executeUsage(os.Stderr, "child_usage.txt", UsageDataChild{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Child) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false

	c.FlagSet = flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	c.FlagSet.Usage = c.Usage

	// Create a local flagset so it doesn't ExitOnError or panic
	fs := flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	fs.Usage = c.Usage

	fs.StringVar(&c.goFlag, "goFlag", c.goFlag, "")
	fs.StringVar(&c.goFlag, "go-flag", c.goFlag, "")

	fs.BoolVar(&c.boolFlag, "boolFlag", c.boolFlag, "")
	fs.BoolVar(&c.boolFlag, "b", c.boolFlag, "")

	fs.Var((*StringSlice)(&c.args), "args", "(positional: true)")

	err = fs.Parse(args)
	if err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}

	remainingArgs = fs.Args()

	// A proper scan handles values attached vs detached and booleans safely to determine exact boundaries
	parsedArgsCount := len(args) - len(remainingArgs)
	if parsedArgsCount > 0 && args[parsedArgsCount-1] == "--" {
		// Verify if it was consumed as a value by the preceding flag
		wasValue := false
		if parsedArgsCount >= 2 {
			prevArg := args[parsedArgsCount-2]
			if len(prevArg) > 0 && prevArg[0] == '-' {
				prevName := prevArg[1:]
				if len(prevName) > 0 && prevName[0] == '-' {
					prevName = prevName[1:]
				}
				eqIdx := -1
				for i, c := range prevName {
					if c == '=' {
						eqIdx = i
						break
					}
				}
				if eqIdx == -1 {
					f := fs.Lookup(prevName)
					if f != nil {
						if bf, ok := f.Value.(interface{ IsBoolFlag() bool }); !ok || !bf.IsBoolFlag() {
							wasValue = true
						}
					}
				}
			}
		}
		if !wasValue {
			dashDashSeen = true
		}
	} else if parsedArgsCount < len(args) && args[parsedArgsCount] == "--" {
		// we didn't consume it.
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("child failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewChild() *Child {
	set := flag.NewFlagSet("child", flag.ContinueOnError)
	v := &Child{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.goFlag, "go-flag", "flag", "TODO: Add usage text")

	set.BoolVar(&v.boolFlag, "b", false, "TODO: Add usage text")

	set.Var((*StringSlice)(&v.args), "args", "(positional: true)")
	set.Usage = v.Usage

	v.CommandAction = func(c *Child) error {

		err := myapp.Child(c.goFlag, c.boolFlag, c.args)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("child failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
