// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"strconv"
	"time"
)

type StringPtrValue struct {
	Target **string
}

func (s *StringPtrValue) Set(val string) error {
	*s.Target = &val
	return nil
}

func (s *StringPtrValue) String() string {
	if *s.Target == nil {
		return ""
	}
	return **s.Target
}

type IntPtrValue struct {
	Target **int
}

func (s *IntPtrValue) Set(val string) error {
	v, err := strconv.Atoi(val)
	if err != nil {
		return err
	}
	*s.Target = &v
	return nil
}

func (s *IntPtrValue) String() string {
	if *s.Target == nil {
		return ""
	}
	return strconv.Itoa(**s.Target)
}

type BoolPtrValue struct {
	Target **bool
}

func (s *BoolPtrValue) Set(val string) error {
	v, err := strconv.ParseBool(val)
	if err != nil {
		return err
	}
	*s.Target = &v
	return nil
}

func (s *BoolPtrValue) String() string {
	if *s.Target == nil {
		return "false"
	}
	return strconv.FormatBool(**s.Target)
}

func (s *BoolPtrValue) IsBoolFlag() bool {
	return true
}

type DurationPtrValue struct {
	Target **time.Duration
}

func (s *DurationPtrValue) Set(val string) error {
	v, err := time.ParseDuration(val)
	if err != nil {
		return err
	}
	*s.Target = &v
	return nil
}

func (s *DurationPtrValue) String() string {
	if *s.Target == nil {
		return "0s"
	}
	return (**s.Target).String()
}
