// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/go-subcommand"
	"github.com/arran4/go-subcommand/cmd"
)

var _ Cmd = (*FormatSourceComments)(nil)

type FormatSourceComments struct {
	*RootCmd
	Flags         *flag.FlagSet
	dir           string
	paths         []string
	recursive     bool
	SubCommands   map[string]Cmd
	CommandAction func(c *FormatSourceComments) error
}

type UsageDataFormatSourceComments struct {
	*FormatSourceComments
	Recursive bool
}

func (c *FormatSourceComments) Usage() {
	err := executeUsage(os.Stderr, "format-source-comments_usage.txt", UsageDataFormatSourceComments{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *FormatSourceComments) UsageRecursive() {
	err := executeUsage(os.Stderr, "format-source-comments_usage.txt", UsageDataFormatSourceComments{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *FormatSourceComments) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "dir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.dir = value

			case "paths", "path":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.paths = append(c.paths, value)

			case "recursive":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.recursive = b
				} else {
					c.recursive = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("format-source-comments failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewFormatSourceComments() *FormatSourceComments {
	set := flag.NewFlagSet("format-source-comments", flag.ContinueOnError)
	v := &FormatSourceComments{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.dir, "dir", ".", "The project root directory containing go.mod")

	set.Var((*StringSlice)(&v.paths), "path", "Paths to search for subcommands relative to dir")

	set.BoolVar(&v.recursive, "recursive", true, "Search recursively")
	set.Usage = v.Usage

	v.CommandAction = func(c *FormatSourceComments) error {

		err := go_subcommand.FormatSourceComments(c.dir, c.paths, c.recursive)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("format-source-comments failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
