// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestFormat_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewFormat()

	called := false
	cmd.CommandAction = func(c *Format) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dir")
	args = append(args, "test")
	args = append(args, "--inplace")
	args = append(args, "--paths")
	args = append(args, "--recursive")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
	if cmd.inplace != true {
		t.Errorf("Expected inplace to be true, got '%v'", cmd.inplace)
	}
	if cmd.recursive != true {
		t.Errorf("Expected recursive to be true, got '%v'", cmd.recursive)
	}
}
