// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestGenerate_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewGenerate()

	called := false
	cmd.CommandAction = func(c *Generate) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dir")
	args = append(args, "test")
	args = append(args, "--manDir")
	args = append(args, "test")
	args = append(args, "--parserName")
	args = append(args, "test")
	args = append(args, "--paths")
	args = append(args, "--recursive")
	args = append(args, "--force")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
	if cmd.manDir != "test" {
		t.Errorf("Expected manDir to be 'test', got '%v'", cmd.manDir)
	}
	if cmd.parserName != "test" {
		t.Errorf("Expected parserName to be 'test', got '%v'", cmd.parserName)
	}
	if cmd.recursive != true {
		t.Errorf("Expected recursive to be true, got '%v'", cmd.recursive)
	}
	if cmd.force != true {
		t.Errorf("Expected force to be true, got '%v'", cmd.force)
	}
}
