// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestGenerateGhRelease_Execute(t *testing.T) {

	parent := &Generate{}
	cmd := parent.NewGenerateGhRelease()

	called := false
	cmd.CommandAction = func(c *GenerateGhRelease) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dir")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
}
