// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"errors"
	go_subcommand "github.com/arran4/go-subcommand"
	"github.com/arran4/go-subcommand/cmd"
)

var _ Cmd = (*Goreleaser)(nil)

type Goreleaser struct {
	*RootCmd
	Flags                *flag.FlagSet
	dir                  string
	githubWorkflow       bool
	verificationWorkflow bool
	prCreationWorkflow   bool
	SubCommands          map[string]func() Cmd
	CommandAction        func(c *Goreleaser) error
}

type UsageDataGoreleaser struct {
	*Goreleaser
	Recursive bool
}

func (c *Goreleaser) Usage() {
	err := executeUsage(os.Stderr, "goreleaser_usage.txt", UsageDataGoreleaser{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Goreleaser) UsageRecursive() {
	err := executeUsage(os.Stderr, "goreleaser_usage.txt", UsageDataGoreleaser{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Goreleaser) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "dir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.dir = value

			case "githubWorkflow", "go-releaser-github-workflow":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.githubWorkflow = b
				} else {
					c.githubWorkflow = true
				}

			case "verificationWorkflow", "verification-workflow":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.verificationWorkflow = b
				} else {
					c.verificationWorkflow = true
				}

			case "prCreationWorkflow", "pr-creation-workflow":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.prCreationWorkflow = b
				} else {
					c.prCreationWorkflow = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("goreleaser failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewGoreleaser() *Goreleaser {
	set := flag.NewFlagSet("goreleaser", flag.ContinueOnError)
	v := &Goreleaser{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.dir, "dir", ".", "The project root directory")

	set.BoolVar(&v.githubWorkflow, "go-releaser-github-workflow", false, "Generate GitHub Actions release workflow")

	set.BoolVar(&v.verificationWorkflow, "verification-workflow", false, "Generate verification workflow")

	set.BoolVar(&v.prCreationWorkflow, "pr-creation-workflow", false, "Generate PR creation workflow")
	set.Usage = v.Usage

	v.CommandAction = func(c *Goreleaser) error {

		err := go_subcommand.Goreleaser(c.dir, c.githubWorkflow, c.verificationWorkflow, c.prCreationWorkflow)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("goreleaser failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
