// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestGoreleaser_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewGoreleaser()

	called := false
	cmd.CommandAction = func(c *Goreleaser) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dir")
	args = append(args, "test")
	args = append(args, "--githubWorkflow")
	args = append(args, "--verificationWorkflow")
	args = append(args, "--prCreationWorkflow")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
	if cmd.githubWorkflow != true {
		t.Errorf("Expected githubWorkflow to be true, got '%v'", cmd.githubWorkflow)
	}
	if cmd.verificationWorkflow != true {
		t.Errorf("Expected verificationWorkflow to be true, got '%v'", cmd.verificationWorkflow)
	}
	if cmd.prCreationWorkflow != true {
		t.Errorf("Expected prCreationWorkflow to be true, got '%v'", cmd.prCreationWorkflow)
	}
}
