// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestInit_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewInit()

	called := false
	cmd.CommandAction = func(c *Init) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dir")
	args = append(args, "test")
	args = append(args, "--goreleaser")
	args = append(args, "--ghRelease")
	args = append(args, "--ghVerification")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
	if cmd.goreleaser != true {
		t.Errorf("Expected goreleaser to be true, got '%v'", cmd.goreleaser)
	}
	if cmd.ghRelease != true {
		t.Errorf("Expected ghRelease to be true, got '%v'", cmd.ghRelease)
	}
	if cmd.ghVerification != true {
		t.Errorf("Expected ghVerification to be true, got '%v'", cmd.ghVerification)
	}
}
