// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

//go:generate sh -c "command -v gosubc >/dev/null 2>&1 && gosubc generate || go run github.com/arran4/go-subcommand/cmd/gosubc generate"

import (
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/cmd"
)

var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

// Provenance
var (
	GeneratorVersion = "(devel)"
	GeneratedAt      = "2026-08-12T01:57:17Z"
	ProjectCommit    = "0c7da877ff1aab983486ab4d8ae9ba20f836386a"
)

func main() {
	root, err := NewRoot("gosubc", version, commit, date)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := root.Execute(os.Args[1:]); err != nil {
		if e, ok := err.(*cmd.ErrExitCode); ok {
			if e.Err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", e.Err)
			}
			os.Exit(e.Code)
		}
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
