// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"testing"
)

func TestRootCmd_Execute_Computed(t *testing.T) {
	t.Parallel()

	cmd, err := NewRoot("test", "v1", "commit", "date")
	if err != nil {
		t.Fatal(err)
	}

	args := []string{}

	if err := cmd.Execute(args); err != nil {
		t.Errorf("Execute() error = %v", err)
	}
}
