// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/go-subcommand"
	"github.com/arran4/go-subcommand/cmd"
)

var _ Cmd = (*Scan)(nil)

type Scan struct {
	*RootCmd
	Flags         *flag.FlagSet
	dir           string
	parserName    string
	paths         []string
	recursive     bool
	SubCommands   map[string]Cmd
	CommandAction func(c *Scan) error
}

type UsageDataScan struct {
	*Scan
	Recursive bool
}

func (c *Scan) Usage() {
	err := executeUsage(os.Stderr, "scan_usage.txt", UsageDataScan{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Scan) UsageRecursive() {
	err := executeUsage(os.Stderr, "scan_usage.txt", UsageDataScan{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Scan) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	processFlag := func(i *int, args []string, flagName string, flagValue string, flagHasValue bool, suffix string) (bool, bool, bool, error) {
		switch flagName {

		case "dir":
			valStr := ""
			usedSuffix := false
			if flagHasValue {
				valStr = flagValue
			} else if suffix != "" {
				valStr = suffix
				usedSuffix = true
			} else {
				if *i+1 < len(args) {
					valStr = args[*i+1]
					*i++
				} else {
					return false, false, false, fmt.Errorf("flag %s requires a value", flagName)
				}
			}
			c.dir = valStr
			return true, usedSuffix, false, nil

		case "parserName", "parser-name":
			valStr := ""
			usedSuffix := false
			if flagHasValue {
				valStr = flagValue
			} else if suffix != "" {
				valStr = suffix
				usedSuffix = true
			} else {
				if *i+1 < len(args) {
					valStr = args[*i+1]
					*i++
				} else {
					return false, false, false, fmt.Errorf("flag %s requires a value", flagName)
				}
			}
			c.parserName = valStr
			return true, usedSuffix, false, nil

		case "paths", "path":
			valStr := ""
			usedSuffix := false
			if flagHasValue {
				valStr = flagValue
			} else if suffix != "" {
				valStr = suffix
				usedSuffix = true
			} else {
				if *i+1 < len(args) {
					valStr = args[*i+1]
					*i++
				} else {
					return false, false, false, fmt.Errorf("flag %s requires a value", flagName)
				}
			}
			c.paths = append(c.paths, valStr)
			return true, usedSuffix, false, nil

		case "recursive":
			if flagHasValue {
				b, err := strconv.ParseBool(flagValue)
				if err != nil {
					return false, false, false, fmt.Errorf("invalid boolean value for flag %s: %s", flagName, flagValue)
				}
				c.recursive = b
			} else {
				c.recursive = true
			}
			return true, false, false, nil
		case "help", "h":
			c.Usage()
			return true, false, true, nil
		}
		return false, false, false, nil
	}

	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")

			found, _, stop, err := processFlag(&i, args, trimmedName, value, hasValue, "")
			if err != nil {
				return err
			}
			if stop {
				return nil
			}
			if found {
				continue
			}

			if strings.HasPrefix(arg, "--") {
				return fmt.Errorf("unknown flag: %s", name)
			}

			remaining := trimmedName
			for len(remaining) > 0 {
				shortName := remaining[0:1]
				loopSuffix := remaining[1:]

				var flagValue string
				var flagHasValue bool

				if len(loopSuffix) == 0 && hasValue {
					flagValue = value
					flagHasValue = true
				}

				found, usedSuffix, stop, err := processFlag(&i, args, shortName, flagValue, flagHasValue, loopSuffix)
				if err != nil {
					return err
				}
				if stop {
					return nil
				}
				if !found {
					return fmt.Errorf("unknown flag: %s", shortName)
				}

				if usedSuffix {
					break
				}
				remaining = loopSuffix
			}

		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("scan failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewScan() *Scan {
	set := flag.NewFlagSet("scan", flag.ContinueOnError)
	v := &Scan{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.dir, "dir", ".", "The project root directory")

	set.StringVar(&v.parserName, "parser-name", "commentv1", "Name of the parser to use")

	set.BoolVar(&v.recursive, "recursive", true, "Search recursively")
	set.Usage = v.Usage

	v.CommandAction = func(c *Scan) error {

		err := go_subcommand.Scan(c.dir, c.parserName, c.paths, c.recursive)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("scan failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
