// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestSkillInspect_Execute(t *testing.T) {

	parent := &Skill{}
	cmd := parent.NewSkillInspect()

	called := false
	cmd.CommandAction = func(c *SkillInspect) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "test")
	args = append(args, "--scope")
	args = append(args, "test")
	args = append(args, "--agent")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.name != "test" {
		t.Errorf("Expected name to be 'test', got '%v'", cmd.name)
	}
	if cmd.scope != "test" {
		t.Errorf("Expected scope to be 'test', got '%v'", cmd.scope)
	}
	if cmd.agent != "test" {
		t.Errorf("Expected agent to be 'test', got '%v'", cmd.agent)
	}
}
