// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"errors"
	go_subcommand "github.com/arran4/go-subcommand"
	"github.com/arran4/go-subcommand/cmd"
)

var _ Cmd = (*SkillList)(nil)

type SkillList struct {
	*Skill
	Flags         *flag.FlagSet
	scope         string
	agent         string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *SkillList) error
}

type UsageDataSkillList struct {
	*SkillList
	Recursive bool
}

func (c *SkillList) Usage() {
	err := executeUsage(os.Stderr, "list_usage.txt", UsageDataSkillList{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SkillList) UsageRecursive() {
	err := executeUsage(os.Stderr, "list_usage.txt", UsageDataSkillList{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SkillList) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "scope":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.scope = value

			case "agent":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.agent = value
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("list failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Skill) NewSkillList() *SkillList {
	set := flag.NewFlagSet("list", flag.ContinueOnError)
	v := &SkillList{
		Skill:       c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.scope, "scope", "user", "The installation scope ('user' or 'project')")

	set.StringVar(&v.agent, "agent", "", "Explicitly target a specific agent (e.g. 'codex', 'claude')")
	set.Usage = v.Usage

	v.CommandAction = func(c *SkillList) error {

		err := go_subcommand.SkillList(c.scope, c.agent)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("list failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
