// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.
//
// Provenance:
// - Version: (devel)
// - Templates: Built-in

package main

import (
	"errors"
	"flag"
	"fmt"
	go_subcommand "github.com/arran4/go-subcommand"
	"github.com/arran4/go-subcommand/cmd"
	"os"
	"slices"
	"strconv"
	"strings"
)

var _ Cmd = (*TemplateExport)(nil)

type TemplateExport struct {
	*Template
	Flags         *flag.FlagSet
	output        string
	asTxtar       bool
	SubCommands   map[string]func() Cmd
	CommandAction func(c *TemplateExport) error
}

type UsageDataTemplateExport struct {
	*TemplateExport
	Recursive bool
}

func (c *TemplateExport) Usage() {
	err := executeUsage(os.Stderr, "export_usage.txt", UsageDataTemplateExport{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *TemplateExport) UsageRecursive() {
	err := executeUsage(os.Stderr, "export_usage.txt", UsageDataTemplateExport{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *TemplateExport) Execute(args []string) error {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "output":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.output = value

			case "asTxtar", "as-txtar":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.asTxtar = b
				} else {
					c.asTxtar = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "o" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.output = value
				}

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("export failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Template) NewTemplateExport() *TemplateExport {
	set := flag.NewFlagSet("export", flag.ContinueOnError)
	v := &TemplateExport{
		Template:    c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.output, "output", "templates", "The destination directory or file.")
	set.StringVar(&v.output, "o", "templates", "The destination directory or file.")

	set.BoolVar(&v.asTxtar, "as-txtar", false, "Export as a txtar archive instead of a directory.")
	set.Usage = v.Usage

	v.CommandAction = func(c *TemplateExport) error {

		err := go_subcommand.TemplateExport(c.output, c.asTxtar)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("export failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
