// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	go_subcommand "github.com/arran4/go-subcommand"
)

var _ Cmd = (*TemplateLayout)(nil)

type TemplateLayout struct {
	*Template
	Flags         *flag.FlagSet
	SubCommands   map[string]func() Cmd
	CommandAction func(c *TemplateLayout) error
}

type UsageDataTemplateLayout struct {
	*TemplateLayout
	Recursive bool
}

func (c *TemplateLayout) Usage() {
	err := executeUsage(os.Stderr, "layout_usage.txt", UsageDataTemplateLayout{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *TemplateLayout) UsageRecursive() {
	err := executeUsage(os.Stderr, "layout_usage.txt", UsageDataTemplateLayout{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *TemplateLayout) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("layout failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Template) NewTemplateLayout() *TemplateLayout {
	set := flag.NewFlagSet("layout", flag.ContinueOnError)
	v := &TemplateLayout{
		Template:    c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *TemplateLayout) error {

		go_subcommand.TemplateLayout()
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
