// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"testing"
)

func TestValidate_Execute_Computed(t *testing.T) {
	t.Parallel()

	root, err := NewRoot("test", "v1", "commit", "date")
	if err != nil {
		t.Fatal(err)
	}

	cmd := root.NewValidate()

	called := false
	cmd.CommandAction = func(c *Validate) error {
		called = true
		return nil
	}

	args := []string{}

	if err := cmd.Execute(args); err != nil {
		t.Errorf("Execute() error = %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}
}
