// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strings"
	"sync"

	"github.com/arran4/go-subcommand/examples/issue455/app"
	"github.com/arran4/go-subcommand/examples/issue455/cmd"
	"github.com/arran4/go-subcommand/examples/issue455/cmd/app/templates"
)

var generatedOpenReader = func(name string) (io.ReadCloser, error) {
	return os.Open(name)
}

var generatedOpenWriter = func(name string) (io.WriteCloser, error) {
	return os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
}

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

func NewLazyCommand(f func() Cmd) func() Cmd {
	var once sync.Once
	var cmd Cmd
	return func() Cmd {
		once.Do(func() {
			cmd = f()
		})
		return cmd
	}
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data any) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]func() Cmd
	Version       string
	Commit        string
	Date          string
	in            []io.Reader
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *RootCmd) UsageRecursive() {
	err := executeUsage(os.Stderr, "app_usage.txt", UsageDataRootCmd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

type UsageDataRootCmd struct {
	*RootCmd
	Recursive bool
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]func() Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.Func("in", "TODO: Add usage text", func(s string) error {
		// Parsed manually in Execute
		return nil
	})

	c.CommandAction = func(c *RootCmd) error {

		err := app.App(c.in)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("app failed: %w", err)
		}
		return nil
	}

	c.Commands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["version"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
				return nil
			},
			UsageFunc: func() {
				fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
			},
		}
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) (err error) {
	var cleanups []func() error
	defer func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			if cerr := cleanups[i](); cerr != nil && err == nil {
				err = cerr
			}
		}
	}()
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "in":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				if value == "-" {
					c.in = append(c.in, os.Stdin)
				} else {
					f, err := generatedOpenReader(value)
					if err != nil {
						return err
					}
					cleanups = append(cleanups, f.Close)
					c.in = append(c.in, f)
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}
	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("app failed: %w", err)
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	return nil
}
