// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/go-subcommand/examples/returns"
	"github.com/arran4/go-subcommand/examples/returns/cmd"
)

var _ Cmd = (*Simple)(nil)

type Simple struct {
	*RootCmd
	Flags         *flag.FlagSet
	fail          bool
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Simple) error
}

type UsageDataSimple struct {
	*Simple
	Recursive bool
}

func (c *Simple) Usage() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) UsageRecursive() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "fail":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.fail = b
				} else {
					c.fail = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "f" {
					found = true
					c.fail = true
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("simple failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewSimple() *Simple {
	set := flag.NewFlagSet("simple", flag.ContinueOnError)
	v := &Simple{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.fail, "fail", false, "Make the command fail")
	set.BoolVar(&v.fail, "f", false, "Make the command fail")
	set.Usage = v.Usage

	v.CommandAction = func(c *Simple) error {

		err := returns.SimpleError(c.fail)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("simple failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
