// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/returns"
)

var _ Cmd = (*Simple)(nil)

type Simple struct {
	*RootCmd
	Flags       *flag.FlagSet
	fail        bool
	SubCommands map[string]Cmd
}

func (c *Simple) Usage() {
	err := executeUsage(os.Stderr, "simple_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	if err := returns.SimpleError(c.fail); err != nil {
		return fmt.Errorf("simple failed: %w", err)
	}

	return nil
}

func (c *RootCmd) NewSimple() *Simple {
	set := flag.NewFlagSet("simple", flag.ContinueOnError)
	v := &Simple{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.fail, "fail", false, "Make the command fail")
	set.BoolVar(&v.fail, "f", false, "Make the command fail")
	set.Usage = v.Usage

	return v
}
