// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/go-subcommand/examples/returns"
)

var _ Cmd = (*Simple)(nil)

type Simple struct {
	*RootCmd
	Flags       *flag.FlagSet
	fail        bool
	SubCommands map[string]Cmd
}

type UsageDataSimple struct {
	*Simple
	Recursive bool
}

func (c *Simple) Usage() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) UsageRecursive() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "fail", "f":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.fail = b
				} else {
					c.fail = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := returns.SimpleError(c.fail); err != nil {
		return fmt.Errorf("simple failed: %w", err)
	}

	return nil
}

func (c *RootCmd) NewSimple() *Simple {
	set := flag.NewFlagSet("simple", flag.ContinueOnError)
	v := &Simple{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.fail, "f", false, "Make the command fail")
	set.BoolVar(&v.fail, "fail", false, "Make the command fail")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
