// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/go-subcommand/examples/nested"
)

var _ Cmd = (*leafCmd)(nil)

type leafCmd struct {
	*subCmd
	Flags *flag.FlagSet

	SubCommands map[string]Cmd
}

func (c *leafCmd) Usage() {
	err := executeUsage(os.Stderr, "leaf_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *leafCmd) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}

	main.Leaf()

	return nil
}

func (c *subCmd) NewleafCmd() *leafCmd {
	set := flag.NewFlagSet("leaf", flag.ContinueOnError)
	v := &leafCmd{
		subCmd:      c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.Usage = v.Usage

	return v
}
